version: '3'

services:
    api:
      container_name: ${COMPOSE_PROJECT_NAME}_back
#      image: testdockerzzitne.azurecr.io/symfony/system
      build:
        context: build
        dockerfile: Dockerfile
      volumes:
        - ../:/var/www/html
      ports:
        - ${DOCKER_APP_PORT}:80
      restart: always
      tty: true
      networks:
        - shared_default

    app:
      container_name: ${COMPOSE_PROJECT_NAME}_front
      image: node:18-alpine
      volumes:
        - ../:/var/www/html
      ports:
        - 3000:3000
        - 24678:24678
      restart: always
      tty: true
      networks:
        - shared_default

networks:
  shared_default:
    external: true