version: '3'

services:
  database:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    command: --init-file /data/application/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD_ROOT}
    volumes:
      - ./build/init.sql:/data/application/init.sql
      - dbdata:/var/lib/mysql/

  phpmyadmin:
    image: phpmyadmin
    container_name: phpMyAdmin
    depends_on:
      - database
    ports:
      - "8080:80"
    environment:
      PMA_ARBITRARY: 1
      PMA_HOST: database
#      PMA_USER: root
#      PMA_PASSWORD: 'notSecureChangeMe'

volumes:
  dbdata:
    driver: local